INSERT INTO departamentos_tabladepartamento (`departamento`)
VALUES
	('ANTIOQUIA'),
	('ATLÁNTICO'),
	('BOGOTÁ, D.C.'),
	('BOLÍVAR'),
	('BOYACÁ'),
	('CALDAS'),
	('CAQUETÁ'),
	('CAUCA'),
	('CESAR'),
	('CÓRDOBA'),
	('CUNDINAMARCA'),
	('CHOCÓ'),
	('HUILA'),
	('LA GUAJIRA'),
	('MAGDALENA'),
	('META'),
	('NARIÑO'),
	('NORTE DE SANTANDER'),
	('QUINDIO'),
	('RISARALDA'),
	('SANTANDER'),
	('SUCRE'),
	('TOLIMA'),
	('VALLE DEL CAUCA'),
	('ARAUCA'),
	('CASANARE'),
	('PUTUMAYO'),
	('ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA'),
	('AMAZONAS'),
	('GUAINÍA'),
	('GUAVIARE'),
	('VAUPÉS'),
	('VICHADA');